
trigger:
- develop

resources:
  containers:
    - container: Django_Container
      image: verencelola/custom_ubuntu
    - container: redis
      image: redis
    - container: postgres
      image: postgres

pool:
  vmImage: 'ubuntu-latest'

container: 'Django_Container'
services:
  redis: redis
  postgres: postgres

steps:

  - script: |
      sudo pip install -r requirements.txt
    displayName: 'Install requirements'
  
  - script: |
      echo 'REDIS_URL=redis://redis:6379' | tee -a .env 
      echo DATABASE_URL=postgres://postgres@postgres:5432 | tee -a .env
      echo SECRET_KEY=$APPLICATION_SECRET | tee -a .env
    displayName: 'Save env to .env'

  - script: |
      python -m pip install flake8
      flake8 .
    displayName: 'Run lint tests'

  - script: |
      pip install pytest
      pip install pytest-cov
      pytest --doctest-modules --junitxml=junit/test-results.xml --cov=com --cov-report=xml --cov-report=html
    displayName: 'Test with pytest'

  - task: PublishTestResults@2
    condition: succeededOrFailed()
    inputs:
      testResultsFiles: '**/test-*.xml'
      testRunTitle: 'Publish test results for Python $(python.version)'

  - task: PublishCodeCoverageResults@1
    inputs:
      codeCoverageTool: Cobertura
      summaryFileLocation: '$(System.DefaultWorkingDirectory)/**/coverage.xml'
      reportDirectory: '$(System.DefaultWorkingDirectory)/**/htmlcov'
