
trigger:
- develop

resources:
  containers:
    - container: Django_Container
      image: ubuntu:16.04
    - container: redis
      image: redis
    - container: postgres
      image: postgres

pool:
  vmImage: 'ubuntu-latest'

container: Django_Container
services:
  redis: redis
  postgres: postgres

strategy:
  matrix:
    Python 3.6:
      PYTHON_VERSION: '3.6'
    Python 3.7:
      PYTHON_VERSION: '3.7'
  maxParallel: 2

steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(PYTHON_VERSION)'
      architecture: 'x64'

  - script: apt-get install libpq-dev python3-dev
    displayName: 'Install tools to fix psycopy2 install errors'

  - script: pip install -r requirements.txt
    displayName: 'Install requirements'

  - script: |
      python -m pip install flake8
      flake8 .
    displayName: 'Run lint tests'

  - script: |
      pip install pytest
      pip install pytest-cov
      pytest tests --doctest-modules --junitxml=junit/test-results.xml --cov=com --cov-report=xml --cov-report=html
    displayName: 'Test with pytest'
    env:
      REDIS_URL: $(REDIS_URL)
      DATABASE_URL: $(POSTGRESQL_URL)
      SECRET_KEY: $(SECRET_KEY)

  - task: PublishTestResults@2
    condition: succeededOrFailed()
    inputs:
      testResultsFiles: '**/test-*.xml'
      testRunTitle: 'Publish test results for Python $(python.version)'

  - task: PublishCodeCoverageResults@1
    inputs:
      codeCoverageTool: Cobertura
      summaryFileLocation: '$(System.DefaultWorkingDirectory)/**/coverage.xml'
      reportDirectory: '$(System.DefaultWorkingDirectory)/**/htmlcov'
